"""add position confirmation and team settings

Revision ID: 0a946a2ead56
Revises: 7719d676a93f
Create Date: 2026-01-30 04:34:09.432482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a946a2ead56'
down_revision: Union[str, None] = '7719d676a93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_settings_id'), 'team_settings', ['id'], unique=False)
    op.add_column('positions', sa.Column('is_info_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'is_info_confirmed')
    op.drop_index(op.f('ix_team_settings_id'), table_name='team_settings')
    op.drop_table('team_settings')
    # ### end Alembic commands ###
