"""update team_settings for currency

Revision ID: 31d1ff85437c
Revises: 784f595bad40
Create Date: 2026-02-03 01:04:12.981023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31d1ff85437c'
down_revision: Union[str, None] = '784f595bad40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_settings', sa.Column('initial_capital_krw', sa.Numeric(precision=20, scale=0), nullable=True))
    op.add_column('team_settings', sa.Column('initial_capital_usd', sa.Numeric(precision=20, scale=2), nullable=True))
    op.add_column('team_settings', sa.Column('exchange_history', sa.JSON(), nullable=True))

    # 기존 데이터 마이그레이션: initial_capital → initial_capital_krw
    op.execute('UPDATE team_settings SET initial_capital_krw = COALESCE(initial_capital, 0)')

    op.drop_column('team_settings', 'initial_capital')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_settings', sa.Column('initial_capital', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True))
    op.drop_column('team_settings', 'exchange_history')
    op.drop_column('team_settings', 'initial_capital_usd')
    op.drop_column('team_settings', 'initial_capital_krw')
    # ### end Alembic commands ###
