"""add buy_plan to position

Revision ID: 3c04268d2e20
Revises: 0a946a2ead56
Create Date: 2026-02-02 09:53:49.955076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c04268d2e20'
down_revision: Union[str, None] = '0a946a2ead56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('buy_plan', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'buy_plan')
    # ### end Alembic commands ###
