"""add new buy request fields

Revision ID: 7719d676a93f
Revises: 517f6789460a
Create Date: 2026-01-30 00:03:14.445989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7719d676a93f'
down_revision: Union[str, None] = '517f6789460a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('ticker_name', sa.String(length=100), nullable=True))
    op.add_column('requests', sa.Column('order_type', sa.String(length=20), nullable=True))
    op.add_column('requests', sa.Column('order_amount', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('requests', sa.Column('order_quantity', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('requests', sa.Column('buy_price', sa.Numeric(precision=20, scale=4), nullable=True))
    op.add_column('requests', sa.Column('memo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'memo')
    op.drop_column('requests', 'buy_price')
    op.drop_column('requests', 'order_quantity')
    op.drop_column('requests', 'order_amount')
    op.drop_column('requests', 'order_type')
    op.drop_column('requests', 'ticker_name')
    # ### end Alembic commands ###
