"""add position_id to discussions

Revision ID: 784f595bad40
Revises: 4d12a3b45c67
Create Date: 2026-02-02 15:17:35.428536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784f595bad40'
down_revision: Union[str, None] = '4d12a3b45c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discussions', sa.Column('position_id', sa.Integer(), nullable=True))
    op.alter_column('discussions', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'discussions', 'positions', ['position_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'discussions', type_='foreignkey')
    op.alter_column('discussions', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('discussions', 'position_id')
    # ### end Alembic commands ###
